### ISSUE TITLE
Design morphology Release Cards and Details Page

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-search-webapp#110]
connects #109

**Comment by kenjinp** [comment]
![Screen Shot 2018-10-22 at 16.51.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae7335e24284b0011eb9fe8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f16b7191a379e90c2e50415f46be5d4a1f06a3a3dc78e2a436628f0d5eead26f0d75946b43afbd8a1fbf00e821dd4c85e3ee9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58f44ae84457a41a3665f43b.png)

First pass on the Search Result Snippet

**Comment by kenjinp** [comment]
You can find an example of the Morphology release instance here [https://bbp-nexus.epfl.ch/staging/explorer/thalamusproject/simulation/morphologyrelease/v0.1.2/effa469e-4781-4454-9dc4-ea8942695dfb](https://bbp-nexus.epfl.ch/staging/explorer/thalamusproject/simulation/morphologyrelease/v0.1.2/effa469e-4781-4454-9dc4-ea8942695dfb) although you may need to manually navigate to it...

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#213
