### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by elisabettai** [BlueBrain/nexus-search-webapp#117]
It seems that I don't have the rights to access search-app, I was able to access it some weeks ago. @kenjinp suggested that it may be due to V1. 

![image](https://user-images.githubusercontent.com/18575092/47865042-7ab4d000-ddfb-11e8-8781-dc3486794b3b.png)

**Comment by kenjinp** [comment]
Access will be more restricted until changes are made to the Search App, for this has been resolved by asking DKE and Backend to offer a change in ACLS for the SearchApp project on production. 

Related to https://github.com/BlueBrain/nexus/issues/223
