### ISSUE TITLE
Welcome text boxes reappear  

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#21]
### Expected behavior

When I click on 'Got It' and 'Thanks' I expect these boxes to vanish when I reload the page.

### Actual Behavior

When I reload the page in the same tab (https://bbp-nexus.epfl.ch/staging/search/) the two boxes appear again.

### Steps to reproduce the problem

1. Open the page
2. Click on the 'Got it' and 'thank you'
3. Reload the page

### Optional infrastructural data (user, platform, browser, environment, ...)

Chrome

**Comment by kenjinp** [comment]
These messages have been removed for the moment. 

However, before removing them, I did persist their state inside local storage!
