### ISSUE TITLE
Sorting icons seem to be missing for some elements

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#23]
### Expected behavior

I expect to sort for any element

### Actual Behavior

Sorting missing for some elements:

![screen shot 2018-08-10 at 09 46 50](https://user-images.githubusercontent.com/12729291/43945507-8f08ecfe-9c82-11e8-841a-d2d81d4db6ed.png)

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#173
