### ISSUE TITLE
Main image in elements might be missing

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#24]
### Expected behavior

When I inspect an entry I expect to see the morphology

### Actual Behavior

In some cases I do not see it

![screen shot 2018-08-10 at 10 22 58](https://user-images.githubusercontent.com/12729291/43947114-828b5976-9c87-11e8-933c-cc9ae71ae0c0.png)

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#174
