### ISSUE TITLE
Inspect elements not shown in a nice way

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#28]
When looking at the details of an instance they are not shown to me in a nice way:

![screen shot 2018-08-10 at 11 14 29](https://user-images.githubusercontent.com/12729291/43950269-20ecd204-9c90-11e8-86c1-c401923463ed.png)

- Just a 'block' of text
- Mixed small and capital letters
- No description/labels

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#178
