### ISSUE TITLE
"Extensions" still missing

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#36]
Extensions are missing. 

![screen shot 2018-08-10 at 14 33 25](https://user-images.githubusercontent.com/12729291/43958075-65c0c40c-9caa-11e8-9ad7-1bc85189147c.png)

What is the purpose of these three tabs anyway?

**Comment by kenjinp** [comment]
Extensions are removed for bespoke details pages for the moment
