### ISSUE TITLE
Extension - Analysis: Unable to scroll down

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#41]
When looking at the Analysis in the Extensions I find that I am not able to scroll down to view it in its entirety. I see maybe half of the image presented, but I cannot scroll down to see it all:

![selection_411](https://user-images.githubusercontent.com/12729291/44322567-33e74900-a44e-11e8-8f6a-47a2fd78581c.png)

Problem on firefox and google chrome.

**Comment by kenjinp** [comment]
extensions have been removed in the recent versions.
