### ISSUE TITLE
Extension - Tools: Jupyter notebook bad link?

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-search-webapp#43]
When I choose a model and click on the link "Analysis in Jupyter notebook" in the Extensions -> Tools section I get back to the search app main window...

**Comment by antonelepfl** [comment]
Yeah that is because we don't have so far a jupyter notebook to analysis an e-model.
I have created a ticket for it (https://github.com/BlueBrain/nexus-search-webapp/issues/44)
