### ISSUE TITLE
Generate a Jupyter Notebook to analyze e-model

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/nexus-search-webapp#44]
We should create a Jupyter Notebook that serves scientists to do some analysis of e-models in some meaningful way.

**Comment by kenjinp** [comment]
Sounds very cool, I don't know anything about Jupyter notebook or how they're used to analyse e-models. You have some ideas?

**Comment by antonelepfl** [comment]
I don't know what scientist want/can do with an e-model so probably we will have so assign this item to some expert on this topic

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#189
