### ISSUE TITLE
Feature Checklist

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-search-webapp#7]
### Big list of webapp features TODO ✅

- "Notification" component with warning, error, and normal
- session timeout message
- shadow box for visualizations
- shareable html metadata with helmet react
- "there was an error, contact support or make issue"
- i18n support
- get configuration object remotely
- feedback mechanism for primary entities
- bucket / shopping cart feature
- query to curl
- copy bearer-token from user dropdown, for people who wants to use API

**Comment by kenjinp** [comment]
html metadata for individual instances are not possible unless we do server-side rendering!

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#166
